name: Promote Docker Image
on: 
  workflow_dispatch: 
    inputs:
      ENV:
        required: true
        description: 'Environment'
        default: 'dev'
      IMAGE_NAME:
        required: true
        description: 'Image name'
      TAG: 
       required: true
       description: 'Image tag'
       
jobs: 
  promote-image:
    runs-on: sw-ubuntu-latest
    steps:
      - uses: sherwin-williams-co/sw-promote-docker-image-composite-action@main
        if: ${{ github.event.inputs.ENV != 'dev' }}
        with:
          environment: ${{ github.event.inputs.ENV }}
          image_name: ${{ github.event.inputs.IMAGE_NAME }}
          image_tag: ${{ github.event.inputs.TAG }}
          artifactory_secret: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
