## This workflow will publish gradle jar into sherwin artifactory i.e https://artifactory.sherwin.com. 
## Before committing the workflow file update the runs-on to our "sw-" self-hosted runners
name: Gradle build jar files and deploy to artifactory

on: 
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
    
jobs:
  build-jar-deploy:
    runs-on: sw-ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      
      - name: Set-up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    
      - name: Build gradle jar and deploy to artifactory
        uses: gradle/gradle-build-action@v2.1.4
        with:
          arguments: -Dorg.gradle.internal.publish.checksums.insecure=true publish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
